"""Contracts for `metermaid export-aggregate`'s restricted export (M4 PR2).

Covers the allowlisted row schema, the mandatory field/sample preview
before any write, and privacy-safe generated bytes: seeded forbidden
canaries for a raw session id, an opaque project key, and a model name
must never appear in the written export, whichever agent/event mix
produced it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import pytest
from pytest import MonkeyPatch

from metermaid.cli import main
from metermaid.domain import NormalizedEvent
from metermaid.export_v1 import (
    ROW_FIELDS,
    SCHEMA_VERSION,
    build_export,
    export_preview,
    render_export,
    write_export,
)
from metermaid.state import load_or_create_secret, resolve_state_paths
from metermaid.store import EventStore

_T0 = datetime(2026, 8, 16, 0, 0, tzinfo=UTC)

# Seeded canaries: values that must never survive into export bytes.
_CANARY_SESSION_ID = "5" * 64
_CANARY_PROJECT_KEY = "7" * 64
_CANARY_MODEL = "canary-forbidden-model"
_CANARY_PROVENANCE = "canary-forbidden-provenance"


def _event(
    *,
    event_id: str = "1" * 64,
    agent: str = "codex",
    source_session_id: str = _CANARY_SESSION_ID,
    project_key: str = _CANARY_PROJECT_KEY,
    occurred_at: datetime = _T0,
    provenance: str = _CANARY_PROVENANCE,
    model: str | None = _CANARY_MODEL,
    tokens_in: int | None = None,
    tokens_out: int | None = None,
    cache_read: int | None = None,
    cache_write: int | None = None,
    reasoning_tokens: int | None = None,
    provider_cost_usd: float | None = None,
) -> NormalizedEvent:
    return NormalizedEvent(
        event_id=event_id,
        agent=agent,
        source_session_id=source_session_id,
        project_key=project_key,
        occurred_at=occurred_at,
        record_kind="usage",
        provenance=provenance,
        model=model,
        tokens_in=tokens_in,
        tokens_out=tokens_out,
        cache_read=cache_read,
        cache_write=cache_write,
        reasoning_tokens=reasoning_tokens,
        provider_cost_usd=provider_cost_usd,
    )


# --- schema: allowlisted fields and aggregation ------------------------------


def test_row_fields_is_the_complete_allowlist() -> None:
    assert ROW_FIELDS == (
        "agent",
        "event_count",
        "session_count",
        "tokens_in",
        "tokens_out",
        "cache_read",
        "cache_write",
        "reasoning_tokens",
        "provider_cost_usd",
    )


def test_build_export_on_no_events_has_no_rows() -> None:
    document = build_export([])
    assert document.schema_version == SCHEMA_VERSION
    assert document.rows == ()


def test_build_export_groups_by_agent_and_sums_observed_counters() -> None:
    events = [
        _event(event_id="1" * 64, agent="codex", tokens_in=100, tokens_out=20),
        _event(event_id="2" * 64, agent="codex", tokens_in=50, tokens_out=None),
        _event(event_id="3" * 64, agent="pi", tokens_in=None, tokens_out=None),
    ]

    document = build_export(events)

    rows = {row.agent: row for row in document.rows}
    assert set(rows) == {"codex", "pi"}
    assert rows["codex"].event_count == 2
    assert rows["codex"].tokens_in == 150
    assert rows["codex"].tokens_out == 20
    assert rows["pi"].event_count == 1
    assert rows["pi"].tokens_in is None


def test_build_export_leaves_a_totally_unobserved_counter_as_none() -> None:
    document = build_export([_event(event_id="1" * 64, cache_read=None)])
    assert document.rows[0].cache_read is None


def test_build_export_distinguishes_an_observed_zero_from_missing() -> None:
    document = build_export([_event(event_id="1" * 64, tokens_out=0)])
    assert document.rows[0].tokens_out == 0


# --- preview: fields and sample must render before any write ----------------


def test_export_preview_lists_every_allowlisted_field() -> None:
    document = build_export([_event(event_id="1" * 64)])
    preview = export_preview(document)
    for field in ROW_FIELDS:
        assert field in preview


def test_export_preview_on_empty_document_states_there_is_no_sample() -> None:
    preview = export_preview(build_export([]))
    assert "no rows" in preview


def test_export_preview_sample_matches_the_first_rendered_row() -> None:
    document = build_export(
        [_event(event_id="1" * 64, agent="codex", tokens_in=7, tokens_out=3)]
    )
    preview = export_preview(document)
    rendered = json.loads(render_export(document))
    sample_json = preview.splitlines()[-1].removeprefix("sample: ")
    assert json.loads(sample_json) == rendered["rows"][0]


# --- canaries: forbidden fields never reach rendered/written bytes ----------


def test_render_export_never_contains_the_forbidden_session_or_project_id() -> None:
    document = build_export(
        [
            _event(
                event_id="1" * 64,
                source_session_id=_CANARY_SESSION_ID,
                project_key=_CANARY_PROJECT_KEY,
            )
        ]
    )
    rendered = render_export(document)
    assert _CANARY_SESSION_ID not in rendered
    assert _CANARY_PROJECT_KEY not in rendered


def test_render_export_never_contains_the_forbidden_model_or_provenance() -> None:
    document = build_export(
        [
            _event(
                event_id="1" * 64,
                model=_CANARY_MODEL,
                provenance=_CANARY_PROVENANCE,
            )
        ]
    )
    rendered = render_export(document)
    assert _CANARY_MODEL not in rendered
    assert _CANARY_PROVENANCE not in rendered


def test_write_export_bytes_never_contain_forbidden_canaries(
    tmp_path: Path,
) -> None:
    document = build_export(
        [
            _event(
                event_id="1" * 64,
                agent="codex",
                source_session_id=_CANARY_SESSION_ID,
                project_key=_CANARY_PROJECT_KEY,
                model=_CANARY_MODEL,
                provenance=_CANARY_PROVENANCE,
                tokens_in=10,
            ),
            _event(
                event_id="2" * 64,
                agent="pi",
                source_session_id="6" * 64,
                project_key="8" * 64,
                model="another-canary-model",
                provenance="another-canary-provenance",
                tokens_in=5,
            ),
        ]
    )
    out = tmp_path / "aggregate.json"

    write_export(document, out)

    raw = out.read_bytes()
    for forbidden in (
        "1" * 64,
        "2" * 64,
        _CANARY_SESSION_ID,
        _CANARY_PROJECT_KEY,
        _CANARY_MODEL,
        _CANARY_PROVENANCE,
        "6" * 64,
        "8" * 64,
        "another-canary-model",
        "another-canary-provenance",
    ):
        assert forbidden.encode() not in raw


def test_write_export_bytes_contain_only_the_allowlisted_field_names(
    tmp_path: Path,
) -> None:
    document = build_export([_event(event_id="1" * 64, agent="codex")])
    out = tmp_path / "aggregate.json"

    write_export(document, out)

    payload = json.loads(out.read_bytes())
    assert payload["schema_version"] == SCHEMA_VERSION
    for row in payload["rows"]:
        assert set(row) == set(ROW_FIELDS)


# --- CLI: `metermaid export-aggregate` ---------------------------------------


def _seed_store(tmp_path: Path) -> Path:
    data_dir = tmp_path / "state"
    paths = resolve_state_paths(data_dir)
    load_or_create_secret(paths)
    store = EventStore(paths.database)
    store.initialize()
    store.commit_ingest(
        [
            _event(
                event_id="1" * 64,
                agent="codex",
                source_session_id=_CANARY_SESSION_ID,
                project_key=_CANARY_PROJECT_KEY,
                model=_CANARY_MODEL,
                provenance=_CANARY_PROVENANCE,
                tokens_in=100,
                tokens_out=20,
                provider_cost_usd=0.25,
            ),
            _event(
                event_id="2" * 64,
                agent="pi",
                source_session_id="6" * 64,
                project_key="8" * 64,
                model=None,
                tokens_in=None,
                tokens_out=None,
            ),
        ],
        [],
        None,
    )
    return data_dir


def test_export_aggregate_command_prints_preview_before_writing(
    monkeypatch: MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    data_dir = _seed_store(tmp_path)
    out = tmp_path / "out.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "metermaid",
            "export-aggregate",
            "--data-dir",
            str(data_dir),
            "--out",
            str(out),
        ],
    )

    main()

    printed = capsys.readouterr().out
    for field in ROW_FIELDS:
        assert field in printed
    assert "sample:" in printed
    assert out.exists()


def test_export_aggregate_command_writes_a_file_with_no_forbidden_canaries(
    monkeypatch: MonkeyPatch, tmp_path: Path
) -> None:
    data_dir = _seed_store(tmp_path)
    out = tmp_path / "out.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "metermaid",
            "export-aggregate",
            "--data-dir",
            str(data_dir),
            "--out",
            str(out),
        ],
    )

    main()

    raw = out.read_bytes()
    for forbidden in (
        _CANARY_SESSION_ID,
        _CANARY_PROJECT_KEY,
        _CANARY_MODEL,
        _CANARY_PROVENANCE,
        "6" * 64,
        "8" * 64,
        str(data_dir),
    ):
        assert forbidden.encode() not in raw

    payload = json.loads(raw)
    agents = {row["agent"] for row in payload["rows"]}
    assert agents == {"codex", "pi"}


def test_export_aggregate_command_console_output_has_no_forbidden_canaries(
    monkeypatch: MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    data_dir = _seed_store(tmp_path)
    out = tmp_path / "out.json"
    monkeypatch.setattr(
        "sys.argv",
        [
            "metermaid",
            "export-aggregate",
            "--data-dir",
            str(data_dir),
            "--out",
            str(out),
        ],
    )

    main()

    printed = capsys.readouterr().out
    assert _CANARY_SESSION_ID not in printed
    assert _CANARY_PROJECT_KEY not in printed
    assert _CANARY_MODEL not in printed
